server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  #instance:
    #prefer-ip-address: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF