server:
  port: 8181
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&autoReconnect=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    validation-query: SELECT 1;
    initial-size: 2
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
mongodb:
  url: localhost
  port: 27017
  username: root
  password: 123456
  dbname: axon
  events:
    collection:
      name: events
    snapshot:
      collection:
        name: snapshots