server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
axon:
  eventhandling:
    processors:
      name:
        mode: tracking
        source: eventBus
spring:
  application:
    name: test_demo
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      url: localhost
      port: 27017
#      username: root
#      password: 123456
      dbname: axon
      events:
        collection:
          name: events
        snapshot:
          collection:
            name: snapshots
      primary:
        uri: mongodb://localhost:27017/testdemo1
      secondary:
        uri: mongodb://localhost:27017/testdemo2
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    validation-query: SELECT 1
    initial-size: 2
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json

